name: pip_services3_redis
version: 1.1.0
description: This framework is part of the [Pip.Services](https://github.com/pip-services/pip-services) project. It contains Redis components RedisCache and RedisLock
homepage: https://github.com/pip-services3-dart/pip-services3-prometheus-dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  pip_services3_commons: ^1.1.3
  pip_services3_components: ^1.1.2
  redis: ^2.0.0
  
dev_dependencies:
  test: ^1.17.12