name: pip_services3_redis
version: 1.0.0
author: Sergey Seroukhov <seroukhov@gmail.com>
description: This framework is part of the [Pip.Services](https://github.com/pip-services/pip-services) project. It contains Redis components RedisCache and RedisLock
homepage: https://github.com/pip-services3-dart/pip-services3-prometheus-dart

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  pip_services3_commons: ">=1.0.4 <2.0.0"
  pip_services3_components: ">=1.0.2 <2.0.0"
  redis: ^1.3.0
  
dev_dependencies:
  test: '>=1.14.2 <2.0.0'